name: Electron CI Build (unsigned)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

defaults:
  run:
    working-directory: src

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            target: mac
            args: --mac
          - os: windows-2022
            target: win
            args: --win
          - os: ubuntu-latest
            target: linux
            # まずは AppImage のみにすると通りやすい（必要なら --linux deb を後で足す）
            args: --linux AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            src/package-lock.json
            src/npm-shrinkwrap.json
            src/yarn.lock

      - name: Cache Electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - name: Print versions
        run: |
          node -v
          npm -v
          npx electron -v || true
          npx electron-builder --version || true

      - name: Install deps (ci if lockfile, otherwise install)
        shell: bash
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "Lockfile found → npm ci"
            npm ci
          else
            echo "No lockfile → npm install"
            npm install
          fi

      - name: Build (unsigned) with log
        shell: bash
        run: |
          mkdir -p ../logs
          npx electron-builder ${{ matrix.args }} -p never 2>&1 | tee ../logs/builder-${{ matrix.target }}.log
        env:
          ELECTRON_CACHE: ~/.cache/electron
          ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: List outputs (debug)
        shell: bash
        run: |
          echo "== src directory =="
          ls -la
          echo "== dist directory =="
          ls -la dist || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-dist
          # working-directory は src なので、リポジトリルート基準で src/dist を指定
          path: src/dist/**/*
          if-no-files-found: error

      - name: Upload builder logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-logs
          path: logs/**
          if-no-files-found: warn

   release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Show assets (debug)
        run: |
          find ./artifacts -type f -ls

      - name: Create GitHub Release with assets (gh)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF#refs/tags/}"

          # すべてのファイルを配列に格納（ディレクトリ混入を回避）
          mapfile -t FILES < <(find ./artifacts -type f -size +0c)

          # 既に同タグのリリースがあれば消して作り直したい場合は次の1行を有効化
          # gh release delete "$TAG" -y || true

          # 作成と同時に資産を添付（公開リリース / 最新扱い）
          gh release create "$TAG" "${FILES[@]}" \
            --title "$TAG" \
            --notes "Automated release for $TAG" \
            --latest

