name: Electron CI Build (unsigned)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    defaults:
      run:
        working-directory: src

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            target: mac
            args: --mac
            glob: |
              src/dist/*.dmg
              src/dist/*-mac*.zip
          - os: windows-2022
            target: win
            args: --win
            glob: |
              src/dist/*.exe
              src/dist/*.msi
              src/dist/*-win*.zip
          - os: ubuntu-latest
            target: linux
            args: --linux AppImage
            glob: |
              src/dist/*.AppImage
              src/dist/*.deb
              src/dist/*.rpm
              src/dist/*.snap

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            src/package-lock.json
            src/npm-shrinkwrap.json
            src/yarn.lock

      - name: Cache Electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - name: Print versions
        run: |
          node -v
          npm -v
          npx electron-builder --version || true

      - name: Install deps
        shell: bash
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (unsigned) with log
        shell: bash
        run: |
          mkdir -p ../logs
          npx electron-builder ${{ matrix.args }} -p never 2>&1 | tee ../logs/builder-${{ matrix.target }}.log
        env:
          ELECTRON_CACHE: ~/.cache/electron
          ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: List outputs (debug)
        shell: bash
        run: |
          echo "== dist =="
          ls -la dist || true

      # ← OSごとに“配布物だけ”をアップロード
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-dist
          path: ${{ matrix.glob }}
          if-no-files-found: error

      - name: Upload builder logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-logs
          path: logs/**
          if-no-files-found: warn

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for gh/git context)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Show assets (debug)
        run: |
          find ./artifacts -type f -ls || true

      - name: Determine tag name
        id: tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create/Update GitHub Release (gh)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ steps.tag.outputs.tag }}"

          # リリースに添付する“配布物だけ”を選別
          mapfile -t FILES < <(find ./artifacts -type f \( \
              -name '*.dmg' -o -name '*-mac*.zip' -o \
              -name '*.exe' -o -name '*.msi' -o -name '*-win*.zip' -o \
              -name '*.AppImage' -o -name '*.deb' -o -name '*.rpm' -o -name '*.snap' \
            \) -size +0c)

          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No distributable files found under ./artifacts"; exit 1
          fi

          if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
            echo "Release $TAG exists. Uploading assets..."
            if ! gh release upload "$TAG" "${FILES[@]}" --clobber --repo "$REPO"; then
              echo "Upload failed (immutable or blocked). Recreating release..."
              gh release delete "$TAG" -y --repo "$REPO" || true
              gh release create "$TAG" "${FILES[@]}" \
                --title "$TAG" \
                --notes "Automated release for $TAG" \
                --latest \
                --repo "$REPO"
            fi
          else
            echo "Creating new release $TAG"
            gh release create "$TAG" "${FILES[@]}" \
              --title "$TAG" \
              --notes "Automated release for $TAG" \
              --latest \
              --repo "$REPO"
          fi

