name: Electron CI Build (unsigned)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14        
            target: mac
            args: --mac
          - os: windows-latest
            target: win
            args: --win
          - os: ubuntu-latest
            target: linux
            args: --linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache Electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Build (unsigned)
        run: npx electron-builder ${{ matrix.args }} -p never
        env:
          ELECTRON_CACHE: ~/.cache/electron
          ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder
          # mac の自動署名検出を完全オフ
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          # 明示的に無署名にしたい場合は下記も空にできる（任意）
          # CSC_LINK: ""
          # WIN_CSC_LINK: ""

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-dist
          path: dist/**/*
          if-no-files-found: error

  # タグ push 時に GitHub Releases を作成
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

